### ISSUE TITLE
fix: TypeError: Cannot read property 'getBufferAsync' of undefined

### ISSUE THREAD

**Issue by petermetz** [luisalvesmartins/Markdown-Mermaid-Expand-to-PNG#2]
1. Install the extension
2. Create a samples.md file
3. Paste the markdown contents into `samples.md` from the documentation of the VSCode extension
4. Attempt to generate the PNG files from the code using the extension
5. Crash happens

```sh
[2021-07-12 11:56:47.722] [exthost] [info] ExtensionService#_doActivateExtension LuisAlvesMartins.markdown-code-to-png {"startup":false,"extensionId":{"value":"LuisAlvesMartins.markdown-code-to-png","_lower":"luisalvesmartins.markdown-code-to-png"},"activationEvent":"onCommand:markdown-code-to-png.topng"}
[2021-07-12 11:56:47.723] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/****/.vscode/extensions/luisalvesmartins.markdown-code-to-png-1.2.1/out/extension.js
[2021-07-12 11:56:48.325] [exthost] [error] TypeError: Cannot read property 'getBufferAsync' of undefined
	at /home/****/.vscode/extensions/luisalvesmartins.markdown-code-to-png-1.2.1/out/extension.js:59:44
	at Generator.throw (<anonymous>)
	at rejected (/home/****/.vscode/extensions/luisalvesmartins.markdown-code-to-png-1.2.1/out/extension.js:6:65) markdown-code-to-png.topng
[2021-07-12 12:01:15.435] [exthost] [error] TypeError: Cannot read property 'getBufferAsync' of undefined
	at /home/****/.vscode/extensions/luisalvesmartins.markdown-code-to-png-1.2.1/out/extension.js:59:44
	at Generator.throw (<anonymous>)
	at rejected (/home/****/.vscode/extensions/luisalvesmartins.markdown-code-to-png-1.2.1/out/extension.js:6:65) markdown-code-to-png.topng
[2021-07-12 12:02:48.523] [exthost] [info] extension host terminating: renderer closed the socket
```

**Comment by luisalvesmartins** [comment]
Hi, can you please try with this markdown below to check if it raises the same error?

A graph:

```mermaid
graph LR
    Start --> Stop
```

**Comment by petermetz** [comment]
@luisalvesmartins Same behavior unfortunately

![Screenshot from 2021-07-19 11-02-19](https://user-images.githubusercontent.com/1583231/126206042-ff38f649-ed19-4756-9efe-53b7e40dab3e.png)

**Comment by luisalvesmartins** [comment]
Are you using CRLF ? or just LF? Can you please ensure you are using CRLF?

**Comment by petermetz** [comment]
@luisalvesmartins Switching to CLRF fixed it. Any chance that the extension could support LF in the future as well?

**Comment by ArnaudBrun** [comment]
Hello,
I'm getting the same issue despite using CRLF, could you help me ?

**Comment by luisalvesmartins** [comment]
> Hello, I'm getting the same issue despite using CRLF, could you help me ?

What is the enconding you are using? Can you please share a sample file to test?

**Comment by ArnaudBrun** [comment]
I'm using UTF-8 encoding.
You'll find attached a sample. Thanks in advance for you help :)

[sample.md](https://github.com/luisalvesmartins/Markdown-Mermaid-Expand-to-PNG/files/12333210/sample.md)

**Comment by luisalvesmartins** [comment]
It worked out of the box:
<img width="427" alt="image" src="https://github.com/luisalvesmartins/Markdown-Mermaid-Expand-to-PNG/assets/643089/e07103de-2312-4494-a1a4-f06424e2f4e3">
I will do more tests on your file
